{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.185968","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.187184","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.187378","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.188116","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.189104","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.189235","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.189341","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.287003","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.687176","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:34.187304","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:34.187843","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.598580","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.605822","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.606262","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.607426","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.607671","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.608509","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.609601","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.609744","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.609848","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.707146","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:30.107376","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:34.607556","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:34.608217","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.104569","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.123103","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.123503","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.124576","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.124801","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.125620","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.126528","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.126660","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.126767","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.224148","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.624460","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:35.124670","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:35.125293","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.211725","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.217406","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.217815","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.218465","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.218612","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.219272","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.220086","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.220205","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.220308","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.318344","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.718470","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:35.218586","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:35.219106","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.304455","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.309949","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.310303","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.311141","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.311310","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.311985","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.312849","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.312967","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.313068","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.410965","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.811123","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:35.311260","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:35.311836","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.775126","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.782140","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.782515","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.783618","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.783813","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.784578","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.785569","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.785695","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.785801","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.883355","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:31.283551","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:35.783741","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:35.784292","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.772499","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.778706","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.779094","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.780187","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.780374","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.781183","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.782156","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.782285","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.782389","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.879987","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:31.280146","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:35.780305","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:35.780778","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:31.100655","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:31.106315","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:31.106655","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:31.107705","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:31.107895","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:31.108604","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:31.109503","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:31.109625","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:31.109725","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:31.207436","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:31.607628","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:36.107822","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:36.108392","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.633149","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.638697","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.639034","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.640089","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.640273","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.640986","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.641861","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.641980","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.642078","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.739847","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:32.140051","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:36.640203","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:36.640781","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:31.833968","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:31.839775","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:31.840138","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:31.840906","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:31.841049","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:31.841625","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:31.842368","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:31.842487","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:31.842586","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:31.940804","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:32.340917","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:36.841027","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:36.841454","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.294476","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.299476","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.299828","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.300569","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.300719","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.301279","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.301992","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.302111","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.302213","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.400380","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.800541","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:37.300690","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:37.301181","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.479214","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.485390","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.485741","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.486632","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.486807","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.487527","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.488499","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.488618","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.488718","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.586470","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.986610","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:37.486757","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:37.487369","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.517909","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.523428","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.523791","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.524597","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.524753","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.525435","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.526129","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.526249","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.526347","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.624357","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:33.024549","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:37.524719","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:37.525230","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.469388","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.474996","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.475353","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.476436","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.476626","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.477371","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.478426","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.478547","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.478648","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.576116","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.976329","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:37.476559","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:37.477074","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.933581","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.939093","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.939459","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.940325","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.940500","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.941205","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.942123","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.942244","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.942344","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:33.040204","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:33.440358","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:37.940456","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:37.941056","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.053786","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.059592","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.059971","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.060832","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.061000","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.061655","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.062529","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.062648","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.062749","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.160706","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.560840","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:38.060950","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:38.061499","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:32.953568","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:32.960514","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:32.960945","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:32.962145","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:32.962350","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:32.963296","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:32.964786","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:32.964952","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:32.965059","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:33.061885","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:33.462080","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:37.962264","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:37.962791","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.404647","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.410311","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.410698","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.411445","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.411712","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.412335","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.413098","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.413233","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.413340","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.511278","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.911401","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:38.411538","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:38.411981","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.840392","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.845988","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.846338","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.847270","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.847441","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.848172","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.849078","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.849196","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.849303","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.947086","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:34.347229","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:38.847388","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:38.847948","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.630274","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.635823","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.636193","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.637078","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.637253","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.638027","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.639070","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.639201","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.639304","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.736909","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:34.137071","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:38.637196","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:38.637756","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.784883","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.790152","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.790504","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.791498","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.791656","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.792324","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.793227","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.793350","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.793449","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.891184","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:34.291422","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:38.791603","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:38.792079","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.218782","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.224687","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.225042","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.226171","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.226358","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.227071","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.228045","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.228174","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.228274","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.325966","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.726130","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:39.226296","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:39.226943","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.278384","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.283995","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.284358","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.285209","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.285374","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.286075","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.286945","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.287071","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.287168","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.385039","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.785195","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:39.285328","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:39.285856","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.501197","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.508037","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.508407","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.509193","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.509366","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.510041","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.510950","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.511073","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.511182","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.609057","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:35.009189","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:39.509318","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:39.509873","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.601585","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.607588","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.607952","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.608880","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.609047","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.609828","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.610744","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.610857","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.610956","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.708692","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:35.108843","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:39.609005","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:39.609597","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.058471","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.064770","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.065158","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.066046","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.066232","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.067018","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.068131","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.068268","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.068368","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.165883","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.566011","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:40.066166","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:40.066729","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.118280","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.123457","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.123782","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.124498","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.124639","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.125179","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.125878","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.125991","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.126089","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.224395","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.624516","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:40.124617","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:40.125158","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.160308","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.167202","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.167622","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.168613","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.168794","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.169553","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.170494","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.170616","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.170716","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.268425","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.668587","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:40.168758","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:40.169324","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.361146","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.367072","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.367431","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.368244","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.368406","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.369026","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.369772","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.369890","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.369986","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.468164","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.868288","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:40.368376","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:40.368910","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.368116","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.374204","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.374581","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.375451","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.375601","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.376171","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.376897","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.377010","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.377109","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.475265","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.875386","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:40.375573","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:40.376118","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.513956","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.521267","nav_name":"api_risk_event","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.521693","nav_name":"api_risk_event","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.522742","nav_name":"api_risk_event","action":"组件启动","params":"数据窗口函数-1, 定时任务函数-0","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.522945","nav_name":"api_risk_event","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.523722","nav_name":"api_risk_event","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.524821","nav_name":"api_risk_event","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.524964","nav_name":"api_risk_event","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.525071","nav_name":"api_risk_event","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.622598","nav_name":"api_risk_event","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:36.022734","nav_name":"api_risk_event","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:40.522876","nav_name":"api_risk_event","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:40.523483","nav_name":"api_risk_event","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:18:35.760229","nav_name":"api_risk_event","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
