{"user":"x_finder3","timestamp":"2024-05-23T10:32:40.817563","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:40.818157","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:35:35.360942","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:35:51.283297","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:35:51.289400","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:35:51.289884","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:35:51.290604","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:35:51.290762","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:35:51.290936","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:36:33.182418","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 173, in Events\n    response_body = ujson.loads(o.get(\"response_body\",\"\"))\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nujson.JSONDecodeError: Unexpected character found when decoding 'null'\n","operate_result":"错误","failed_reason":"Unexpected character found when decoding 'null'"}
{"user":"x_finder3","timestamp":"2024-05-23T10:36:35.763266","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 173, in Events\n    response_body = ujson.loads(o.get(\"response_body\",\"\"))\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nujson.JSONDecodeError: Expected object or value\n","operate_result":"错误","failed_reason":"Expected object or value"}
{"user":"x_finder3","timestamp":"2024-05-23T10:36:37.590496","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 173, in Events\n    response_body = ujson.loads(o.get(\"response_body\",\"\"))\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nujson.JSONDecodeError: Expected object or value\n","operate_result":"错误","failed_reason":"Expected object or value"}
{"user":"x_finder3","timestamp":"2024-05-23T10:36:37.592310","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 173, in Events\n    response_body = ujson.loads(o.get(\"response_body\",\"\"))\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nujson.JSONDecodeError: Expected object or value\n","operate_result":"错误","failed_reason":"Expected object or value"}
{"user":"x_finder3","timestamp":"2024-05-23T10:36:37.592577","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 173, in Events\n    response_body = ujson.loads(o.get(\"response_body\",\"\"))\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nujson.JSONDecodeError: Expected object or value\n","operate_result":"错误","failed_reason":"Expected object or value"}
{"user":"x_finder3","timestamp":"2024-05-23T10:36:53.580967","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 173, in Events\n    response_body = ujson.loads(o.get(\"response_body\",\"\"))\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nujson.JSONDecodeError: Expected object or value\n","operate_result":"错误","failed_reason":"Expected object or value"}
{"user":"x_finder3","timestamp":"2024-05-23T10:37:49.029233","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 173, in Events\n    response_body = ujson.loads(o.get(\"response_body\",\"\"))\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nujson.JSONDecodeError: Expected object or value\n","operate_result":"错误","failed_reason":"Expected object or value"}
{"user":"x_finder3","timestamp":"2024-05-23T10:39:43.119813","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:39:43.125168","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:39:43.125605","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:39:43.126240","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:39:43.126381","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:39:43.126527","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:50:28.877796","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:16:21.065848","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:16:21.218347","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:16:36.119407","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:16:36.125168","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:16:36.125489","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:16:36.126420","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:16:36.126623","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:16:36.126775","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:17:15.757253","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 219, in Events\n    ret_res=label_data(value_lst,value,label_info_dict,ret_res)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 300, in label_data\n    event.setdefault(name,value_lst)\n                     ^^^^\nNameError: name 'name' is not defined\n","operate_result":"错误","failed_reason":"name 'name' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T11:17:53.923311","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:18:03.854765","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:18:18.490774","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:18:18.496693","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:18:18.497092","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:18:18.497869","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:18:18.498031","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:18:18.498203","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:18:57.208659","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 206, in Events\n    event=label_data(value_lst,value,label_info_dict,event,name)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 300, in label_data\n    event.setdefault(name,value_lst)\n    ^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'setdefault'\n","operate_result":"错误","failed_reason":"'NoneType' object has no attribute 'setdefault'"}
{"user":"x_finder3","timestamp":"2024-05-23T11:19:16.431638","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 206, in Events\n    event=label_data(value_lst,value,label_info_dict,event,name)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 300, in label_data\n    event.setdefault(name,value_lst)\n    ^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'setdefault'\n","operate_result":"错误","failed_reason":"'NoneType' object has no attribute 'setdefault'"}
{"user":"x_finder3","timestamp":"2024-05-23T11:19:16.443144","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 206, in Events\n    event=label_data(value_lst,value,label_info_dict,event,name)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 300, in label_data\n    event.setdefault(name,value_lst)\n    ^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'setdefault'\n","operate_result":"错误","failed_reason":"'NoneType' object has no attribute 'setdefault'"}
{"user":"x_finder3","timestamp":"2024-05-23T11:19:26.026074","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 206, in Events\n    event=label_data(value_lst,value,label_info_dict,event,name)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 300, in label_data\n    event.setdefault(name,value_lst)\n    ^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'setdefault'\n","operate_result":"错误","failed_reason":"'NoneType' object has no attribute 'setdefault'"}
{"user":"x_finder3","timestamp":"2024-05-23T11:19:29.685061","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 206, in Events\n    event=label_data(value_lst,value,label_info_dict,event,name)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 300, in label_data\n    event.setdefault(name,value_lst)\n    ^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'setdefault'\n","operate_result":"错误","failed_reason":"'NoneType' object has no attribute 'setdefault'"}
{"user":"x_finder3","timestamp":"2024-05-23T11:19:32.148475","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 206, in Events\n    event=label_data(value_lst,value,label_info_dict,event,name)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 300, in label_data\n    event.setdefault(name,value_lst)\n    ^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'setdefault'\n","operate_result":"错误","failed_reason":"'NoneType' object has no attribute 'setdefault'"}
{"user":"x_finder3","timestamp":"2024-05-23T11:20:57.029015","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:20:57.034736","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:20:57.035127","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:20:57.035756","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:20:57.035913","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:20:57.036090","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:29:57.494002","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:32:12.849712","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T11:43:39.482488","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T16:59:58.463584","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T17:00:16.479755","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T17:00:16.485203","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T17:00:16.485541","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T17:00:16.486125","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T17:00:16.486268","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T17:00:16.486411","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T17:05:14.809158","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:05:14.820103","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:05:14.820690","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:05:34.458475","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:05:34.653126","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:09.423741","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:11.488736","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:15.986976","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:16.078554","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:16.331331","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:16.433158","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:16.685968","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:16.787619","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:16.888899","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:17.141453","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:37.944204","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:38.046992","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:38.047651","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:38.048126","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:38.048871","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:38.049339","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:38.049994","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:38.050882","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:08:38.051350","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:17:19.274274","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:17:19.275274","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:17:19.276002","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:17:19.276510","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 230, in Events\n    event_dic = {\"url\":url,\"time\":iso_to_datetime(o[\"time\"]),\"cookie\":o.get(\"cookie\"),\"flow_id\":o.get(\"flow_id\",\"\"),\"app\":o.get(\"app\"),\"account\":o.get(\"account\"),\"name\":url_name,\"parameter\":o.get(\"parameter\"),\"app_name\":o.get(\"app_name\"),\"id\":o.get(\"id\"),\"dstip\":o.get(\"dstip\"),\"user_info\": o.get(\"user_info\"),\"event\":event,\"request_body\":o.get(\"request_body\",\"\"),\"response_body\":o.get(\"response_body\",\"\"),\"res\":ret_res,\"action\":action_name,\"status_msg\":status_msg}\n                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'status_msg' where it is not associated with a value\n","operate_result":"错误","failed_reason":"cannot access local variable 'status_msg' where it is not associated with a value"}
{"user":"x_finder3","timestamp":"2024-05-23T17:39:30.359366","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T17:39:46.376731","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T17:39:46.382442","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T17:39:46.382809","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T17:39:46.383654","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T17:39:46.383838","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T17:39:46.383990","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-24T10:22:10.390974","nav_name":"api_operation_event_new","action":"ST处理","params":"st_30f","operate_result":"错误","failed_reason":"错误跟踪：Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/__init__.py\", line 812, in store_ckh2\n    stream[\"CKH\"].execute('INSERT INTO %s (%s) VALUES'%(table,\",\".join(keys))"}
{"user":"x_finder3","timestamp":"2024-05-24T10:23:40.415308","nav_name":"api_operation_event_new","action":"ST处理","params":"st_30f","operate_result":"错误","failed_reason":"错误跟踪：Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/__init__.py\", line 812, in store_ckh2\n    stream[\"CKH\"].execute('INSERT INTO %s (%s) VALUES'%(table,\",\".join(keys))"}
{"user":"x_finder3","timestamp":"2024-05-24T10:24:40.431470","nav_name":"api_operation_event_new","action":"ST处理","params":"st_30f","operate_result":"错误","failed_reason":"错误跟踪：Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/__init__.py\", line 812, in store_ckh2\n    stream[\"CKH\"].execute('INSERT INTO %s (%s) VALUES'%(table,\",\".join(keys))"}
{"user":"x_finder3","timestamp":"2024-05-24T10:55:10.480711","nav_name":"api_operation_event_new","action":"ST处理","params":"st_30f","operate_result":"错误","failed_reason":"错误跟踪：Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/__init__.py\", line 812, in store_ckh2\n    stream[\"CKH\"].execute('INSERT INTO %s (%s) VALUES'%(table,\",\".join(keys))"}
{"user":"x_finder3","timestamp":"2024-05-24T14:02:10.250081","nav_name":"api_operation_event_new","action":"ST处理","params":"st_30f","operate_result":"错误","failed_reason":"错误跟踪：Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/__init__.py\", line 812, in store_ckh2\n    stream[\"CKH\"].execute('INSERT INTO %s (%s) VALUES'%(table,\",\".join(keys))"}
{"user":"x_finder3","timestamp":"2024-05-24T15:16:10.230827","nav_name":"api_operation_event_new","action":"ST处理","params":"st_30f","operate_result":"错误","failed_reason":"错误跟踪：Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/__init__.py\", line 812, in store_ckh2\n    stream[\"CKH\"].execute('INSERT INTO %s (%s) VALUES'%(table,\",\".join(keys))"}
{"user":"x_finder3","timestamp":"2024-05-27T10:29:10.978944","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-27T10:29:10.984686","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-27T10:29:10.985062","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-27T10:29:10.985994","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-27T10:29:10.986892","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-27T10:29:10.987559","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-27T10:31:56.893063","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-27T10:31:57.053536","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-27T10:31:57.214653","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-27T10:58:05.399484","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-27T10:58:05.405250","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-27T10:58:05.405633","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-27T10:58:05.406254","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-27T10:58:05.406403","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-27T10:58:05.406568","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-30T08:51:40.380439","nav_name":"api_operation_event_new","action":"ST处理","params":"st_30f","operate_result":"错误","failed_reason":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 1128, in xlink_core.st_thread\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 259, in print30\n    o"}
{"user":"x_finder3","timestamp":"2024-05-30T08:52:10.387409","nav_name":"api_operation_event_new","action":"ST处理","params":"st_30f","operate_result":"错误","failed_reason":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 1128, in xlink_core.st_thread\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 259, in print30\n    o"}
{"user":"x_finder3","timestamp":"2024-05-30T15:11:42.498412","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-30T15:11:42.503728","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-30T15:11:42.504089","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-30T15:11:42.504733","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-30T15:11:42.504885","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-30T15:11:42.505048","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-04T15:03:40.450408","nav_name":"api_operation_event_new","action":"ST处理","params":"st_30f","operate_result":"错误","failed_reason":"错误跟踪：Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/__init__.py\", line 812, in store_ckh2\n    stream[\"CKH\"].execute('INSERT INTO %s (%s) VALUES'%(table,\",\".join(keys))"}
{"user":"x_finder3","timestamp":"2024-06-04T15:06:40.038117","nav_name":"api_operation_event_new","action":"ST处理","params":"st_30f","operate_result":"错误","failed_reason":"错误跟踪：Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/__init__.py\", line 812, in store_ckh2\n    stream[\"CKH\"].execute('INSERT INTO %s (%s) VALUES'%(table,\",\".join(keys))"}
{"user":"x_finder3","timestamp":"2024-06-25T16:57:29.357644","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T16:57:29.363196","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T16:57:29.363562","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T16:57:29.364295","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T16:57:29.364436","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T16:57:29.364581","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:01:49.528908","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:01:49.534130","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:01:49.534501","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:01:49.535103","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:01:49.535254","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:01:49.535421","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:19:38.466378","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:19:38.471237","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:19:38.471627","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:19:38.472280","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:19:38.472438","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:19:38.472603","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:42:53.017436","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:42:53.023211","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:42:53.023529","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:42:53.024299","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:42:53.024437","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-25T17:42:53.024570","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-26T14:46:00.589606","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-26T14:46:00.595873","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-26T14:46:00.596238","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-26T14:46:00.597042","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-26T14:46:00.597207","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-06-26T14:46:00.597350","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-07-31T16:18:18.254637","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-07-31T16:18:18.259937","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-07-31T16:18:18.260319","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-07-31T16:18:18.260915","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-07-31T16:18:18.261064","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-07-31T16:18:18.261234","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-08-01T17:40:42.190813","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-08-01T17:40:42.196891","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-08-01T17:40:42.197209","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-08-01T17:40:42.198019","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-08-01T17:40:42.198183","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-08-01T17:40:42.198334","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
