{"user":"x_finder3","timestamp":"2024-05-22T11:09:58.598029","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:09:58.598969","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:09:58.690874","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:09:58.895015","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:09:59.561817","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:09:59.562797","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:09:59.665137","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:09:59.666045","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:10:00.051281","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:10:00.052157","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:10:00.166168","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:10:00.569248","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:22:47.892167","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:29:33.834926","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:29:33.835656","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:29:33.837306","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:43:17.549788","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:43:17.654842","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:43:18.918832","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:43:42.648835","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:43:42.649529","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:43:42.661717","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:43:48.456844","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:43:48.468806","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:43:48.470282","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:47.487917","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:47.601732","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:47.602506","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:47.603308","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:47.603995","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:47.706146","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:47.797881","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:47.798442","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:47.901704","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:47.902817","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:48.107963","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:58.686084","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:58.688853","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:58.689731","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:58.792254","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:58.793019","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:58.793615","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:58.896619","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:58.897497","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:58.989400","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:59.042582","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T11:44:59.398147","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T14:00:32.621210","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T14:00:32.622495","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T14:00:32.623464","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T14:02:50.171080","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T14:02:50.182893","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T14:02:50.286934","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 231, in Events\n    if v in label_info_dict:#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T14:17:44.147498","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T14:17:56.426197","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T14:17:56.431208","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T14:17:56.431535","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T14:17:56.432133","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T14:17:56.432267","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T14:17:56.432407","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T14:18:06.382799","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 232, in Events\n    if v in label_info_dict and not isinstance(v,list):#如果值存在于字典之中，那么这个字典中的值是列表，就需要将数据取出来\n       ^^^^^^^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T14:20:31.952090","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T14:20:43.675350","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 245, in Events\n    ret_res.setdefault(name,list(set(value_lst)))\n                                 ^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T14:22:19.103890","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 245, in Events\n    ret_res.setdefault(name,list(set(value_lst)))\n                                 ^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T14:22:20.754109","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 245, in Events\n    ret_res.setdefault(name,list(set(value_lst)))\n                                 ^^^^^^^^^^^^^^\nTypeError: unhashable type: 'list'\n","operate_result":"错误","failed_reason":"unhashable type: 'list'"}
{"user":"x_finder3","timestamp":"2024-05-22T14:32:21.466428","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T14:32:21.471920","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T14:32:21.472317","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T14:32:21.472957","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T14:32:21.473112","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T14:32:21.473277","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T14:33:33.646099","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-22T15:48:52.589967","nav_name":"api_operation_event_new","action":"调试","params":"退出调试模式,更新代码!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:31:50.454328","nav_name":"api_operation_event_new","action":"启动参数","params":"unix_udp: \/tmp\/operation_events_new,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:31:50.459425","nav_name":"api_operation_event_new","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:31:50.459838","nav_name":"api_operation_event_new","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:31:50.460581","nav_name":"api_operation_event_new","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:31:50.460722","nav_name":"api_operation_event_new","action":"事件主循环","params":"Unix_UDP 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:31:50.460868","nav_name":"api_operation_event_new","action":"启动完成","params":"Unix_UDP 准备完毕,开始接收消息!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:03.335197","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:03.335576","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:03.335839","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.250142","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.361361","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.361586","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.361845","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.362124","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.372461","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.372646","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.372959","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.373140","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.383534","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.383720","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.464549","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.464772","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.716817","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:05.717076","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:06.976053","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:07.066991","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:07.077305","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:07.077537","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:07.077709","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:07.077934","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:07.078102","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:07.672535","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:07.692937","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:10.251415","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:10.251741","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:10.251956","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:11.722940","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:11.723218","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:11.723442","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:11.733736","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:11.824638","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:11.834932","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:11.835148","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:12.328708","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:12.328959","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:13.437010","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:13.437334","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:13.437556","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:14.958557","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:15.200608","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:15.200890","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:15.211180","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:16.017234","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:16.017574","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:16.763145","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:16.763457","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:16.763679","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:18.385476","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:18.587188","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:18.587431","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:18.587654","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:19.937335","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:19.937590","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:20.038544","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:20.038787","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:22.103710","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:22.103993","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:22.114358","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:23.816815","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:23.817085","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:26.083078","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:26.083397","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:26.093740","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:26.093942","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:26.094168","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:26.094388","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:26.104664","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:26.487747","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:26.488039","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:27.696822","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:27.707148","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:27.717499","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:29.927050","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:29.927338","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:29.927569","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:29.927740","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:31.483085","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:31.483385","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:31.735501","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:31.735793","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:33.045323","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:33.045666","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:33.055973","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:33.056196","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:33.267963","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:33.650951","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:33.651204","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:34.406842","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:34.417216","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:34.417444","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:35.868161","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:36.231116","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:36.231382","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:36.231621","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:36.231800","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:36.232036","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:36.232205","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:36.685628","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:36.695942","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:38.045772","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:38.046027","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:38.046304","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:39.517003","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:40.010790","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:40.011035","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:40.011277","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
{"user":"x_finder3","timestamp":"2024-05-23T10:32:40.011456","nav_name":"api_operation_event_new","action":"事件处理出错","params":"错误跟踪：Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 697, in xlink_core.Main4\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/api_operation_event_new.py\", line 172, in Events\n    tableres= table_common(url,response_body,stream[\"table_dic\"])\n                           ^^^\nNameError: name 'url' is not defined\n","operate_result":"错误","failed_reason":"name 'url' is not defined"}
