{"user":"x_finder3","timestamp":"2024-09-03T10:29:38.890313","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:38.963483","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:39.153098","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:39.199110","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:39.415010","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:39.820518","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:39.784513","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:40.156412","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:40.490873","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:40.795551","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:40.971474","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:41.038747","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:41.311745","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:41.403082","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:41.678695","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:41.900151","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:42.183704","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:42.429109","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:42.790568","nav_name":"modsecurity","action":"初始化出错","params":"错误跟踪:Traceback (most recent call last):\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/xlink_main.py\", line 171, in <module>\n    xlink.Inits()\n  File \"\/opt\/openfbi\/fbi-bin\/addones\/streams\/modsecurity.py\", line 190, in Inits\n    stream[\"libCalc\"] = modsecurity_init()\n                        ^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/openfbi\/pylibs\/modsecurity.py\", line 6, in __init__\n    self.libCalc = CDLL(\"\/opt\/openfbi\/pylibs\/libmod.so\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"\/opt\/fbi-base\/lib\/python3.11\/ctypes\/__init__.py\", line 376, in __init__\n    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: \/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory\n","operate_result":"错误","failed_reason":"初始化出错：\/opt\/openfbi\/pylibs\/libmod.so: cannot open shared object file: No such file or directory"}
